import { z } from 'zod';

export const reportGenSchema = z.object({
  title: z.string().default('Security Assessment Report'),
  target: z.string().describe('Primary target of the assessment'),
  findings: z.array(z.object({
    type: z.string(),
    severity: z.enum(['info', 'low', 'medium', 'high', 'critical']),
    target: z.string(),
    details: z.string(),
    remediation: z.string().optional(),
  })).describe('Security findings'),
  scope: z.array(z.string()).optional().describe('Scope of assessment'),
  methodology: z.string().optional().describe('Testing methodology used'),
  format: z.enum(['markdown', 'json']).default('markdown'),
});

export type ReportGenInput = z.infer<typeof reportGenSchema>;

export async function reportGen(input: ReportGenInput): Promise<{
  success: boolean;
  report: string;
  format: string;
  findingCount: number;
}> {
  const { title, target, findings, scope, methodology, format } = input;

  if (format === 'json') {
    const report = JSON.stringify({
      title,
      target,
      date: new Date().toISOString().split('T')[0],
      scope: scope || [target],
      methodology: methodology || 'Automated security assessment using mcp-vanguard',
      summary: {
        total: findings.length,
        critical: findings.filter(f => f.severity === 'critical').length,
        high: findings.filter(f => f.severity === 'high').length,
        medium: findings.filter(f => f.severity === 'medium').length,
        low: findings.filter(f => f.severity === 'low').length,
        info: findings.filter(f => f.severity === 'info').length,
      },
      findings,
    }, null, 2);

    return { success: true, report, format: 'json', findingCount: findings.length };
  }

  // Markdown format
  const sorted = [...findings].sort((a, b) => {
    const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
    return (order[a.severity] ?? 5) - (order[b.severity] ?? 5);
  });

  const lines: string[] = [
    `# ${title}`,
    '',
    `**Target:** ${target}`,
    `**Date:** ${new Date().toISOString().split('T')[0]}`,
    `**Tool:** mcp-vanguard`,
    '',
    '## Executive Summary',
    '',
    `This assessment identified **${findings.length}** findings:`,
    `- Critical: ${findings.filter(f => f.severity === 'critical').length}`,
    `- High: ${findings.filter(f => f.severity === 'high').length}`,
    `- Medium: ${findings.filter(f => f.severity === 'medium').length}`,
    `- Low: ${findings.filter(f => f.severity === 'low').length}`,
    `- Info: ${findings.filter(f => f.severity === 'info').length}`,
    '',
  ];

  if (scope && scope.length > 0) {
    lines.push('## Scope', '', ...scope.map(s => `- ${s}`), '');
  }

  if (methodology) {
    lines.push('## Methodology', '', methodology, '');
  }

  lines.push('## Findings', '');

  for (let i = 0; i < sorted.length; i++) {
    const f = sorted[i];
    const severityBadge = f.severity.toUpperCase();
    lines.push(
      `### ${i + 1}. [${severityBadge}] ${f.type}`,
      '',
      `**Target:** ${f.target}`,
      '',
      f.details,
      '',
    );
    if (f.remediation) {
      lines.push(`**Remediation:** ${f.remediation}`, '');
    }
    lines.push('---', '');
  }

  lines.push(
    '## Disclaimer',
    '',
    'This report was generated by automated security tools. Findings should be manually verified.',
    'False positives may be present. This assessment does not guarantee the absence of vulnerabilities.',
  );

  return {
    success: true,
    report: lines.join('\n'),
    format: 'markdown',
    findingCount: findings.length,
  };
}
